hibernate.dialect net.sf.hibernate.dialect.MySQLDialect
hibernate.connection.driver_class org.gjt.mm.mysql.Driver
hibernate.connection.url jdbc:mysql://<host>/<database>
hibernate.connection.username <username>
hibernate.connection.password <password>
#hibernate.connection.url jdbc:mysql://localhost/jboss
#hibernate.connection.username jboss
#hibernate.connection.password password


#hibernate.session_factory_name=java:/MySqlDS
#hibernate.jndi.url=jnp://localhost:1099
#hibernate.transaction.manager_lookup_class=org.hibernate.transaction.JBossTransactionManagerLookup
#hibernate.hbm2ddl.auto=create-drop
#hibernate.cache.provider_class=org.hibernate.cache.HashtableCacheProvider
#hibernate.connection.datasource=java:/MySqlDS
#hibernate.dialect=net.sf.hibernate.dialect.MySQLDialect
