#
# File: SigEventsDB.prop
#
# Version: $Id: SigEventsDB.properties,v 1.3 2006/10/03 02:18:19 ntt Exp $
#
#  Copyright (c) 2006 by the California Institute of Technology.          
#  ALL RIGHTS RESERVED.  United States Government Sponsorship      
#  acknowledged. Any commercial use must be negotiated with the      
#  Office of Technology at the California Institute of Technology.  
#                      
#  The technical data in this document (or file) is controlled for     
#  export under the Export Administration Regulations (EAR), 15 CFR,  
#  Parts 730-774. Violations of these laws are subject to fines and    
#  penalties under the Export Administration Act.                      
#
# Description: Define data source for SigEvents 
#
#
SYB_HOSTNAME    = <sybase host>
SYB_PORT        = <sybase port>
SYB_DATABASE    = <database name>
SYB_USER        = <user name>
SYB_PASSWORD    = <user password>
SYB_DESCRIPTION = <description>
